dashboard:
  title: 'Bridge Runtime'
  rows:
    - title: Description
      height: 100px
      panels:
        - title: Description
          content: |
            **This dashboard is managed by [Grafyaml](https://docs.openstack.org/infra/system-config/grafyaml.html).**

            If you would like to make changes to this dashboard, please see the grafana directory in [project-config](https://opendev.org/openstack/project-config/src/grafana/bridge.yaml).
          type: text

    - title: run_all Runtime
      showTitle: true
      height: 400px
      panels:
        - title: "run_all.sh"
          type: graph
          span: 12
          tooltip:
            sort: 1
          yaxes:
            - format: ms
            - show: false
          nullPointMode: connected
          targets:
            - target: aliasSub(stats.timers.bridge.ansible.run_all.*.median, "stats.timers.bridge.ansible.run_all.(.*).median", "\1")
              refId: A

    - title: Individual runtimes
      showTitle: true
      height: 200px
      panels:
        - title: "afs"
          type: graph
          span: 3
          yaxes:
            - format: ms
            - show: false
          nullPointMode: connected
          targets:
            - target: aliasSub(stats.timers.bridge.ansible.run_all.afs.median, "stats.timers.bridge.ansible.run_all.(.*).median", "\1")
              refId: A

        - title: "base"
          type: graph
          span: 3
          yaxes:
            - format: ms
            - show: false
          nullPointMode: connected
          targets:
            - target: aliasSub(stats.timers.bridge.ansible.run_all.base.median, "stats.timers.bridge.ansible.run_all.(.*).median", "\1")
              refId: A

        - title: "bridge"
          type: graph
          span: 3
          yaxes:
            - format: ms
            - show: false
          nullPointMode: connected
          targets:
            - target: aliasSub(stats.timers.bridge.ansible.run_all.bridge.median, "stats.timers.bridge.ansible.run_all.(.*).median", "\1")
              refId: A

        - title: "else"
          type: graph
          span: 3
          yaxes:
            - format: ms
            - show: false
          nullPointMode: connected
          targets:
            - target: aliasSub(stats.timers.bridge.ansible.run_all.else.median, "stats.timers.bridge.ansible.run_all.(.*).median", "\1")
              refId: A

        - title: "git"
          type: graph
          span: 3
          yaxes:
            - format: ms
            - show: false
          nullPointMode: connected
          targets:
            - target: aliasSub(stats.timers.bridge.ansible.run_all.git.median, "stats.timers.bridge.ansible.run_all.(.*).median", "\1")
              refId: A

        - title: "total"
          type: graph
          span: 3
          yaxes:
            - format: ms
            - show: false
          nullPointMode: connected
          targets:
            - target: aliasSub(stats.timers.bridge.ansible.run_all.total.median, "stats.timers.bridge.ansible.run_all.(.*).median", "\1")
              refId: A

        - title: "update_puppet_version"
          type: graph
          span: 3
          yaxes:
            - format: ms
            - show: false
          nullPointMode: connected
          targets:
            - target: aliasSub(stats.timers.bridge.ansible.run_all.update_puppet_version.median, "stats.timers.bridge.ansible.run_all.(.*).median", "\1")
              refId: A

        - title: "update_system_config"
          type: graph
          span: 3
          yaxes:
            - format: ms
            - show: false
          nullPointMode: connected
          targets:
            - target: aliasSub(stats.timers.bridge.ansible.run_all.update_system_config.median, "stats.timers.bridge.ansible.run_all.(.*).median", "\1")
              refId: A

    - title: Cloud launcher runtime
      showTitle: true
      height: 400px
      panels:
        - title: "run_cloud_launcher.sh"
          type: graph
          span: 12
          yaxes:
            - format: ms
            - show: false
          nullPointMode: connected
          targets:
            - target: alias(stats.timers.bridge.ansible.run_cloud_launcher.median, "run_cloud_launcher.sh")
              refId: A
