dashboard:
  title: Kolla Failure Rate
  time:
      from: "now-7d"
      to: "now"
  rows:
    - title: Description
      height: 100px
      panels:
        - title: Description
          content: |
            **This dashboard is managed by [Grafyaml](https://docs.openstack.org/infra/system-config/grafyaml.html).**

            If you would like to make changes to this dashboard, please see the grafana directory in [project-config](https://opendev.org/openstack/project-config/src/grafana/kolla.yaml).
            NOTE - 'No datapoints' in a graph means there have been no job failures reported yet.
          type: text
    - title: Graphs
      height: 320px
      panels:
        - title: Source Build Failure Rates (Check queue)
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_kolla.master.job.kolla-build-centos-source.{FAILURE,TIMED_OUT}),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_kolla.master.job.kolla-build-centos-source.{SUCCESS,FAILURE,TIMED_OUT})),'24hours'), 'kolla-build-centos-source')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_kolla.master.job.kolla-build-ubuntu-source.{FAILURE,TIMED_OUT}),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_kolla.master.job.kolla-build-ubuntu-source.{SUCCESS,FAILURE,TIMED_OUT})),'24hours'), 'kolla-build-ubuntu-source')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_kolla.master.job.kolla-build-oraclelinux-source.{FAILURE,TIMED_OUT}),sum(stats_counts.zuul.tenant.openstack.pipeline.gate.project.opendev_org.openstack_kolla.master.job.kolla-build-oraclelinux-source.{SUCCESS,FAILURE,TIMED_OUT})),'24hours'), 'gate-kolla-build-source-oraclelinux')
          type: graph
        - title: Binary Build Failure Rates (Check queue)
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_kolla.master.job.kolla-build-centos-binary.{FAILURE,TIMED_OUT),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_kolla.master.job.kolla-build-centos-binary.{SUCCESS,FAILURE,TIMED_OUT})),'24hours'), 'kolla-build-centos-binary')
            - target: alias(movingAverage(asPercent(transformNull(sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_kolla.master.job.kolla-build-ubuntu-binary.{FAILURE,TIMED_OUT})),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_kolla.master.job.kolla-build-ubuntu-binary.{SUCCESS,FAILURE,TIMED_OUT})),'24hours'), 'kolla-build-ubuntu-binary')
            - target: alias(movingAverage(asPercent(transformNull(sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_kolla.master.job.kolla-build-oraclelinux-binary{FAILURE,TIMED_OUT})),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_kolla.master.job.kolla-build-oraclelinux-binary.{SUCCESS,FAILURE,TIMED_OUT})),'24hours'), 'kolla-build-oraclelinux-binary')
          type: graph
