dashboard:
  title: "OpenStack-Ansible"
  rows:
    - title: Description
      height: 100px
      panels:
        - title: Description
          content: |
            **This dashboard is managed by [Grafyaml](https://docs.openstack.org/infra/system-config/grafyaml.html).**

            If you would like to make changes to this dashboard, please see the grafana directory in [project-config](https://opendev.org/openstack/project-config/src/grafana/openstack-ansible.yaml).
          type: text
    - title: Ubuntu openstack-ansible check job runtimes
      showTitle: true
      height: 300px
      panels:
        - title: aio_lxc-ubuntu-bionic
          type: graph
          span: 2
          leftYAxisLabel: "time"
          y_formats:
            - s
            - none
          targets:
            - target: alias(scale(averageSeries(stats.timers.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-ubuntu-bionic.{SUCCESS,FAILURE}.mean), '0.001'), 'Average')
        - title: aio_lxc-ubuntu-focal
          type: graph
          span: 2
          leftYAxisLabel: "time"
          y_formats:
            - s
            - none
          targets:
            - target: alias(scale(averageSeries(stats.timers.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-ubuntu-focal.{SUCCESS,FAILURE}.mean), '0.001'), 'Average')
        - title: aio_lxc-debian-buster
          type: graph
          span: 2
          leftYAxisLabel: "time"
          y_formats:
            - s
            - none
          targets:
            - target: alias(scale(averageSeries(stats.timers.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-debian-buster.{SUCCESS,FAILURE}.mean), '0.001'), 'Average')
        - title: aio_metal-ubuntu-bionic
          type: graph
          span: 2
          leftYAxisLabel: "time"
          y_formats:
            - s
            - none
          targets:
            - target: alias(scale(averageSeries(stats.timers.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_metal-ubuntu-bionic.{SUCCESS,FAILURE}.mean), '0.001'), 'Average')
        - title: aio_metal-ubuntu-focal
          type: graph
          span: 2
          leftYAxisLabel: "time"
          y_formats:
            - s
            - none
          targets:
            - target: alias(scale(averageSeries(stats.timers.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_metal-ubuntu-focal.{SUCCESS,FAILURE}.mean), '0.001'), 'Average')
        - title: aio_metal-debian-buster
          type: graph
          span: 2
          leftYAxisLabel: "time"
          y_formats:
            - s
            - none
          targets:
            - target: alias(scale(averageSeries(stats.timers.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_metal-debian-buster.{SUCCESS,FAILURE}.mean), '0.001'), 'Average')


    - title: CentOS openstack-ansible check job runtimes
      showTitle: true
      height: 300px
      panels:
        - title: aio_lxc-centos-7
          type: graph
          span: 3
          leftYAxisLabel: "time"
          y_formats:
            - s
            - none
          targets:
            - target: alias(scale(averageSeries(stats.timers.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-centos-7.{SUCCESS,FAILURE}.mean), '0.001'), 'Average')
        - title: aio_lxc-centos-8
          type: graph
          span: 3
          leftYAxisLabel: "time"
          y_formats:
            - s
            - none
          targets:
            - target: alias(scale(averageSeries(stats.timers.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-centos-8.{SUCCESS,FAILURE}.mean), '0.001'), 'Average')
        - title: aio_metal-centos-7
          type: graph
          span: 3
          leftYAxisLabel: "time"
          y_formats:
            - s
            - none
          targets:
            - target: alias(scale(averageSeries(stats.timers.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_metal-centos-7.{SUCCESS,FAILURE}.mean), '0.001'), 'Average')
        - title: aio_metal-centos-8
          type: graph
          span: 3
          leftYAxisLabel: "time"
          y_formats:
            - s
            - none
          targets:
            - target: alias(scale(averageSeries(stats.timers.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_metal-centos-8.{SUCCESS,FAILURE}.mean), '0.001'), 'Average')


    - title: Custom scenario openstack-ansible check job runtimes
      showTitle: true
      height: 300px
      panels:
        - title: aio_ceph-ubuntu-bionic
          type: graph
          span: 3
          leftYAxisLabel: "time"
          y_formats:
            - s
            - none
          targets:
            - target: alias(scale(averageSeries(stats.timers.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_ceph-ubuntu-bionic.{SUCCESS,FAILURE}.mean), '0.001'), 'Average')
        - title: aio_ceph_ubuntu-focal
          type: graph
          span: 3
          leftYAxisLabel: "time"
          y_formats:
            - s
            - none
          targets:
            - target: alias(scale(averageSeries(stats.timers.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_ceph-ubuntu-focal.{SUCCESS,FAILURE}.mean), '0.001'), 'Average')
        - title: aio_proxy-ubuntu-focal
          type: graph
          span: 3
          leftYAxisLabel: "time"
          y_formats:
            - s
            - none
          targets:
            - target: alias(scale(averageSeries(stats.timers.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_proxy-ubuntu-focal.{SUCCESS,FAILURE}.mean), '0.001'), 'Average')


    - title: openstack-ansible check job success rate
      showTitle: true
      height: 300px
      panels:
        - title: openstack-ansible job success rate (Check queue)
          type: graph
          span: 12
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-ubuntu-focal.SUCCESS),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-ubuntu-focal.{SUCCESS,FAILURE,TIMED_OUT})),'24hours'), 'aio_lxc-ubuntu-focal')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-ubuntu-bionic.SUCCESS),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-ubuntu-bionic.{SUCCESS,FAILURE,TIMED_OUT})),'24hours'), 'aio_lxc-ubuntu-bionic')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_proxy-ubuntu-focal.SUCCESS),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_proxy-ubuntu-focal.{SUCCESS,FAILURE,TIMED_OUT})),'24hours'), 'aio_lxc-ubuntu-bionic')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_ceph-ubuntu-bionic.SUCCESS),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_ceph-ubuntu-bionic.{SUCCESS,FAILURE,TIMED_OUT})),'24hours'), 'aio_lxc-ubuntu-bionic')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_ceph-ubuntu-focal.SUCCESS),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_ceph-ubuntu-focal.{SUCCESS,FAILURE,TIMED_OUT})),'24hours'), 'aio_lxc-ubuntu-bionic')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-centos-7.SUCCESS),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-centos-7.{SUCCESS,FAILURE,TIMED_OUT})),'24hours'), 'aio_lxc-centos-7')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-centos-8.SUCCESS),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-centos-8.{SUCCESS,FAILURE,TIMED_OUT})),'24hours'), 'aio_lxc-centos-8')
    - title: openstack-ansible check job failure rate
      showTitle: true
      height: 300px
      panels:
        - title: openstack-ansible job failure rate (Check queue)
          type: graph
          span: 12
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-ubuntu-focal.FAILURE),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-ubuntu-focal.{SUCCESS,FAILURE,TIMED_OUT})),'24hours'), 'aio_lxc-ubuntu-focal')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-ubuntu-bionic.FAILURE),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-ubuntu-bionic.{SUCCESS,FAILURE,TIMED_OUT})),'24hours'), 'aio_lxc-ubuntu-bionic')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_proxy-ubuntu-focal.FAILURE),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_proxy-ubuntu-focal.{SUCCESS,FAILURE,TIMED_OUT})),'24hours'), 'aio_proxy-ubuntu-focal')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_ceph-ubuntu-bionic.FAILURE),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_ceph-ubuntu-bionic.{SUCCESS,FAILURE,TIMED_OUT})),'24hours'), 'aio_ceph-ubuntu-bionic')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_ceph-ubuntu-focal.FAILURE),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_ceph-ubuntu-focal.{SUCCESS,FAILURE,TIMED_OUT})),'24hours'), 'aio_ceph-ubuntu-focal')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-centos-7.FAILURE),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-centos-7.{SUCCESS,FAILURE,TIMED_OUT})),'24hours'), 'aio_lxc-centos-7')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-centos-8.FAILURE),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-centos-8.{SUCCESS,FAILURE,TIMED_OUT})),'24hours'), 'aio_lxc-centos-8')
    - title: openstack-ansible check job timeout rate (Check queue)
      showTitle: true
      height: 300px
      panels:
        - title: openstack-ansible job timeout rate (Check queue)
          type: graph
          span: 12
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-ubuntu-focal.TIMED_OUT),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-ubuntu-focal.{SUCCESS,FAILURE,TIMED_OUT})),'24hours'), 'lxc-ubuntu-focal')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-ubuntu-bionic.TIMED_OUT),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-ubuntu-bionic.{SUCCESS,FAILURE,TIMED_OUT})),'24hours'), 'aio_lxc-ubuntu-bionic')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_proxy-ubuntu-focal.TIMED_OUT),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_proxy-ubuntu-focal.{SUCCESS,FAILURE,TIMED_OUT})),'24hours'), 'aio_proxy-ubuntu-bionic')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_ceph-ubuntu-bionic.TIMED_OUT),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_ceph-ubuntu-bionic.{SUCCESS,FAILURE,TIMED_OUT})),'24hours'), 'aio_ceph-ubuntu-bionic')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_ceph-ubuntu-focal.TIMED_OUT),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_ceph-ubuntu-focal.{SUCCESS,FAILURE,TIMED_OUT})),'24hours'), 'aio_ceph-ubuntu-focal')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-centos-7.TIMED_OUT),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-centos-7.{SUCCESS,FAILURE,TIMED_OUT})),'24hours'), 'aio_lxc-centos-7')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-centos-8.TIMED_OUT),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-centos-888888887.{SUCCESS,FAILURE,TIMED_OUT})),'24hours'), 'aio_lxc-centos-8')
