- hosts: localhost
  roles:
    - role: create-afs-token
    - role: release-afs-volume
      afs_volume: mirror.wheel.cent7x64
    - role: release-afs-volume
      afs_volume: mirror.wheel.cent8x64
    - role: release-afs-volume
      afs_volume: mirror.wheel.busterx64
    - role: release-afs-volume
      afs_volume: mirror.wheel.focalx64
    - role: release-afs-volume
      afs_volume: mirror.wheel.bionicx64
    - role: release-afs-volume
      afs_volume: mirror.wheel.xenialx64
    - role: destroy-afs-token
