- hosts: all
  tasks:
    - name: Rename tarball and move it to a subdir named dist as well
      # TODO(AJaeger): "-new" is for testing
      shell: |
        mkdir dist
        mv {{ zuul.project.short_name }}*.tar.gz dist/{{ zuul.project.short_name }}-latest-new.tar.gz
      args:
        executable: /bin/bash
        chdir: "{{ zuul.project.src_dir }}/dist"
      # 302 mkdir used in place of argument state=directory to file module
      tags:
        - skip_ansible_lint
